[project]
name = "ArcRaiders-AutoScrapper"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "mss>=10.1.0",
    "numpy>=2.4.0",
    "opencv-python>=4.11.0.86",
    "pillow>=12.0.0",
    "pydirectinput-rgx>=2.1.3",
    "pynput>=1.8.1",
    "pywinctl>=0.4.1",
    "rich>=14.2.0",
    "tessdata-fast-eng>=1.0.0",
    "tesserocr>=2.9.2",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
